### PR TITLE
Server

### LINKED ISSUE #14: Handle std::bad_alloc
We should aim to catch std::bad_alloc specifically in a big try-catch block in order to prevent the server from crashing when it runs out of memory (and pray that it doesn't run out of stack)

### LINKED ISSUE #16: 415 Unsupported media type
related to Content-Encoding header field [(RFC 9110)](https://www.rfc-editor.org/rfc/rfc9110#name-content-encoding)

### LINKED ISSUE #27: [Waiting for cache] Validate content-related header fields
- [x] Content-Type
- [ ] Content-Encoding
- [ ] Content-Language
- [ ] Content-Location
- [ ] (ETag)

### LINKED ISSUE #73: Mime parser

### PR DESCRIPTION
**Pull request by andreaulicna**

### CODE REVIEW

File: src/HttpRequest.cpp [hunk 1]
```diff
@@ -498,6 +498,32 @@ stringpair_t	HttpRequest::parseHeader(octets_t header)
...
+{
+	stringmap_t::iterator											contentType;
+	std::string														contentTypeValue;
+	std::map< std::string, std::set<std::string> >					mimeTypesDict;
+	struct stat														statBuff;
+
+	contentType = this->headerFields.find("content-type");
+	mimeTypesDict = location.getMimeTypes().getMimeTypesDict();
+	if (stat(this->targetResource.c_str(), &statBuff) != 0)
+		throw (ResponseException(500, "Internal Server Error"));
```
Comment (loudapet) [inline src/HttpRequest.cpp:511]: ResponseException should have something like "Failure on stat()" as the second argument, in order to provide more context

File: src/HttpRequest.cpp [hunk 2]
```diff
@@ -498,6 +498,32 @@ stringpair_t	HttpRequest::parseHeader(octets_t header)
...
+	if (contentType != this->headerFields.end()) // content-type found in headerFields
+	{
+	// validate content-type header field
+		contentTypeValue = splitQuotedString(contentType->second, ';')[0];
```
Comment (loudapet) [inline src/HttpRequest.cpp:515]: What happens if it's an empty string?

File: inc/HttpResponse.hpp [hunk 3]
```diff
@@ -21,6 +21,13 @@
 #include "Location.hpp"
 #include "webserv.hpp"
 
+# define NOCGI 0
```
Comment (loudapet) [inline inc/HttpResponse.hpp:24]: Pls no, let's rewrite this into enums

File: src/HttpRequest.cpp [hunk 4]
```diff
@@ -498,6 +498,32 @@ stringpair_t	HttpRequest::parseHeader(octets_t header)
...
+		contentTypeValue = trim(contentTypeValue);
+		std::transform(contentTypeValue.begin(), contentTypeValue.end(), contentTypeValue.begin(), tolower); // case-insensitive
+		std::cout << "CONTENT TYPE: " << contentTypeValue << std::endl;
+	    if (mimeTypesDict.find(contentTypeValue) == mimeTypesDict.end()) // content-type not found in mimeTypesDict
+		{
+			this->response.updateStatus(415, "Unsupported media type");
```
Comment (loudapet) [inline src/HttpRequest.cpp:521]: The second argument provides details, not status explanation (that is encoded in statusDict already) - should say something like "Intended content type not supported by the server"

**Review by loudapet — APPROVED** [review]
